version: '2'
services:
  dev_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dev_db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST_PORT=5432
      - POSTGRES_HOST=dev_db
      - PYTHONDONTWRITEBYTECODE=1
    image: "sweat_connect_api:${BUILD_NUMBER}"
    ports:
      - ${APP_HOST_PORT}:5000
    volumes:
       - ./api:/pythonpath/api
  dev_db:
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    image: postgres:10.3-alpine
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    volumes:
       - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
